
# The User Management System Final Project: Your Epic Coding Adventure Awaits! 🎉✨🔥


## Submission and Grading: 📝✏️📈

1. **Reflection Document**: 

    Word Document Reflection: 
    Document is also submitted by docx on Canvas
        [Document-Reflection](https://docs.google.com/document/d/1tJvMS3v5xDxeEv27Jyo03wQ_FeNKDg3V/edit?usp=sharing&ouid=103582853920917914547&rtpof=true&sd=true)


    QA-Issue & Debugging Branch:
        [5-QA-issues](https://github.com/Livia-1212/user_management_final/tree/1-Bug)

    New Unit Testing:
        [10-NEW-tests](https://github.com/Livia-1212/user_management_final/blob/new-features/tests/test_services/test_analytics_service.py) 

    New Feature Added Branch:
        [NewFeature-Branch](https://github.com/Livia-1212/user_management_final/tree/new-features)

2. **What I have done for New Feature:**

    [New-feature-documentation] (https://github.com/Livia-1212/user_management_final/blob/new-features/new_features.md)

    Docker Repo Link:
        [Link-to-Docker]()  



## Managing the Project Workload: Stay Focused, Stay Victorious ⏱️🧠⚡

**Remaining Issue**

 For Maintain a Working Main Branch: The github workflow action might not pass 100% because Pydantic Core on my end requirements.txt just would not be installed properly. The error is:
'''
    Preparing metadata (pyproject.toml) ... error
    error: subprocess-exited-with-error
    
    × Preparing metadata (pyproject.toml) did not run successfully.
    │ exit code: 1
    ╰─> [6 lines of output]
        
        Cargo, the Rust package manager, is not installed or is not on PATH.
        This package requires Rust and Cargo to compile extensions. Install it through
        the system's package manager or via https://rustup.rs/
        
        Checking for Rust toolchain....
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed

    × Encountered error while generating package metadata.
    ╰─> See above for output.
    note: This is an issue with the package mentioned above, not pip.
'''
